_target_: src.models.components.audio.mel_spectrogram.MelSpectrogram
_partial_: true
sample_rate: 16_000
n_fft: 1024
win_length: 1024
hop_length: 160
f_min: 0
f_max: 8_000
n_mels: 80
normalized: True
center: True