_target_: src.models.components.diffusion.edm_diffusion.EDMDiffusion
_partial_: true
num_frames: ${datamodule.num_frames}
channels: ${model.net.channels}
# cond_drop_prob: 0.1
dynamic_thresholding: True
dynamic_thresholding_percentile: 0.95  # unsure what this was based on perusal of paper
num_sample_steps: 20  # number of sampling steps
sigma_min: 0.002  # min noise level
sigma_max: 80  # max noise level
sigma_data: 0.5  # standard deviation of data distribution
rho: 7  # controls the sampling schedule
P_mean: -1.2  # mean of log-normal distribution from which noise is drawn for training
P_std: 1.2  # standard deviation of log-normal distribution from which noise is drawn for training
S_churn: 80  # parameters for stochastic sampling - depends on dataset, Table 5 in apper
S_tmin: 0.05
S_tmax: 50
S_noise: 1.003
null_cond_prob: 0.  # probability of passing null condition
smooth_weight: 0.0
