# @package _global_

defaults:
  - _self_
  - datamodule: video_datamodule_universal_audio
  - model: video_diffusion_edm
  - logger: null
  - trainer: gpu
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: ""
config_path: ""
load_separetely: False
eval_save_all: False
compile_model: True
filter_run: null